---
title: "`blogcard` shortcode"
date: now
toc: true
format:
    html: default
    typst: default
filters:
   - t-arae/blogcard
---

The `blogcard` shortcode makes it easy to create a card-like link.

## Instalation

To use the `blogcard` extension in your Quarto project, run this command in the terminal from the project's working directory.
This will install the extension under the `_extensions` subdirectory.

```bash
quarto add t-arae/blogcard
```

Then, apply the `blogcard` filter by adding the following lines to the YAML header of your `.qmd` file.

```yaml
filters:
  - t-arae/blogcard
```

## Basic usage

To create a card using the `blogcard` shortcode, write the shortcode directive like this:

```markdown
{{{< blogcard https://quarto.org >}}}
```

{{< blogcard https://quarto.org >}}

The first argument of the `blogcard` shortcode will be used as the URL.

You can also pass the URL through the keyword argument, like this:

```{.markdown}
{{{< blogcard url=https://quarto.org >}}}
or 
{{{< blogcard url="https://quarto.org" >}}}
```

{{< blogcard url="https://quarto.org" >}}

## Template selection

You can select a template using the `tname` attribute:

```{.markdown}
{{{< blogcard https://quarto.org tname="mini" >}}}
```

{{< blogcard https://quarto.org tname="mini" >}}

## When no open graph protocol tags are found

The `blogcard` shortcode uses the content of `<meta>` tag containing the Open Graph Protocol (OGP) to create a card-like link.
If no OGP content is found (or if it fails to retrieve the HTML content),
it generates a simple card.

```{.markdown}
{{{< blogcard https://example.com >}}}
```

{{< blogcard https://example.com >}}

## Manually set the data

You can also set the content manually using keyword arguments:

```{.markdown}
{{{< blogcard https://example.com title="This is title" description="No description" image="https://via.placeholder.com/300x200" >}}}
```

{{< blogcard https://example.com title="This is title" description="No description" image="https://via.placeholder.com/300x200" >}}
